version: '3.8'

services:
  birrpay-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env
    volumes:
      - ./logs:/var/log/birrpay
      - ./ssl:/etc/ssl/birrpay:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - birrpay-network
    depends_on:
      - redis
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - birrpay-network
    depends_on:
      - birrpay-bot

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    networks:
      - birrpay-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    restart: unless-stopped

volumes:
  redis-data:
    driver: local

networks:
  birrpay-network:
    driver: bridge