services:
  - type: web
    name: birrpay-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node complete-admin-bot.js
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: DEBUG_MODE
        value: "false"
      - key: LOG_LEVEL
        value: "error"
      - key: RENDER_EXTERNAL_URL
        value: https://bpayb-24y5.onrender.com
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: birrpay-20e82
      - key: FIREBASE_PRIVATE_KEY_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_CLIENT_ID
        sync: false
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: FIREBASE_AUTH_PROVIDER_X509_CERT_URL
        value: https://www.googleapis.com/oauth2/v1/certs
      - key: FIREBASE_CLIENT_X509_CERT_URL
        sync: false
      - key: WEBHOOK_URL
        value: https://bpayb-24y5.onrender.com/telegram
      - key: ENABLE_FIRESTORE_LISTENER
        value: "true"
      - key: FIREBASE_CONFIG
        sync: false
    autoDeploy: true
    numInstances: 1
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      cpu: 0.1
      memory: 512MB
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block

databases:
  - name: birrpay-secrets
    plan: free