services:
  - type: web
    name: bpayb
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node complete-admin-bot.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ADMIN_TELEGRAM_ID
        value: "5186537254"
      - key: KEEP_ALIVE_URL
        value: https://bpayb.onrender.com
      - key: HEALTH_CHECK_URL
        value: http://localhost:3000/health
      - key: MAX_ERRORS_BEFORE_RECOVERY
        value: 10
      - key: ERROR_WINDOW_MS
        value: 300000
      - key: RECOVERY_WAIT_MS
        value: 30000
      - key: ENABLE_PERFORMANCE_MONITORING
        value: true
      - key: ENABLE_ERROR_LOGGING
        value: true
      - key: ENABLE_HEALTH_CHECKS
        value: true
    autoDeploy: true
    numInstances: 1

databases:
  - name: birrpay-secrets
    plan: free